// <auto-generated />
using AIIL.Services.CourseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIIL.Services.CourseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240910171406_AddCourseToDb")]
    partial class AddCourseToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIIL.Services.CourseAPI.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CategoryId = 1,
                            Description = "A beginner's course for IELTS preparation.",
                            ImageUrl = "https://example.com/images/ielts-intro.jpg",
                            MentorId = 1,
                            Price = 99.99m,
                            Title = "Introduction to IELTS"
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 2,
                            Description = "An advanced course for students looking to master the IELTS exam.",
                            ImageUrl = "https://example.com/images/ielts-advanced.jpg",
                            MentorId = 2,
                            Price = 149.99m,
                            Title = "Advanced IELTS Techniques"
                        },
                        new
                        {
                            CourseId = 3,
                            CategoryId = 1,
                            Description = "Focused on helping students improve their writing skills for IELTS.",
                            ImageUrl = "https://example.com/images/ielts-writing.jpg",
                            MentorId = 1,
                            Price = 79.99m,
                            Title = "IELTS Writing Mastery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
